{% set name = "statuspage" %}
{% set version = "0.8.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4eb5f3bc2ea33f59f0b42c9cd2ef6c909e09069b7c96a71dae32f72dab068b02

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  preserve_egg_dir: True
  entry_points:
    - statuspage = statuspage.statuspage:cli

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pygithub
    - click
    - jinja2
    - tqdm
    - requests
    - markdown2

test:
  commands:
    - statuspage --help

about:
  home: https://github.com/jayfk/statuspage
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A statuspage generator that lets you host your statuspage for free on Github.

extra:
  recipe-maintainers:
    - jakirkham
