travis:
  secure:
    BINSTAR_TOKEN: UEgu5Vql9Zt3NsYzgh0OeP3EtqICW0A2rTqfj7UJYYIW+9r171heHJf4SKTnd+SD1t93z8jBFnLaf8apd3x3qxovhtO8lTEwA3hZWdEMtZ8gs09d71aO0EddmXjDHx4AYSrNuQSZBCN+LTJExpPsX2Wl00Dz/eILuQYUQf29ehr1ljKs89icaGgntVO6Sn3524lwPMyIbN38Lm+WlMA+NueXz7/WzqlZGZ5TkVOizupunjsp2G/8szSUd7STgxuVa6qCNy5TVIq1JPfuH4seQzzuOY7/mPE7P5/1qjNDQBMnSQf6Tdy6cKZTkplJL9+6ra8SKnQxHhtxpArzZYEb87EeuFlSjL1/Vae/uAV16nN6cOByodRMZfupk3DvgJl9wu/JSWKGNi7YxGJmGg8y78y8wafXRTEL2gU0By0wrOm/yTO7MPmV3rTyJLJYighjYW6xKbpmTcjJw1yp070Eycau0k2XkZpxnzBzwLAbXHSUb2KNqM9JiNB7nni6N9OkImf9feLdVBUjJ7AShovVZum96xkvfmfwF3lju8sp5c5kH1Rxzx5n1cCBfEroKTnYYf0dcdRGilzU0sDv1R6VlHpYEVYTGlqsgWQl7WZyn5hKHECJGUWuMhYdlPqM9OBec9jO49h/P7i25OCqzoLWR0vifNt/fWr5+ynQhGujmEs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
