travis:
  secure:
    BINSTAR_TOKEN: GBvh7MkODMfinetSgHDscnZDLppZd2t91UHoQhR2GG2IIyCzSh/FkW8LQnKF56wuSfH1emyf1dlBCv/OKepYVbgYnEnQFY565aFMsLKzGqhRscKYmKwdcrOt0zmo7C9KU7jTFrDX0O7DcYfRi/Ei9JcG5ZhqL10w3pQ7JRI74M3UPnIxa4tBN7d+Wbdc49d11j23Lc30H6kZFvHe+uXGuRzY3fSp82+ZixF8XdJx4Yoc8K8FgbmSZOaljkOki/HWMrA4TAVehuRQM+8Hjw4jQQeY9gnF9LaYoYVQ56lTwgcEPA5g9APqlB6NEp5ugCrFp5k9pLH4ZNR6Paq1YpPDRsGJMqf7pj8r9EGqSlwoNe9ffqWiCBkq7xRJQOWUZCauHmzyM+zFN58EMDScZzprlzjluNl80ZY3CMFg+Mxd5h0vhEFTE8/P85n4JH338mKaPc/+O1oo4NFdD7B6xjmobQEBSO4VklYbqWKx4aOw0Xr0C80Yg+i4lvFbxT3LFqPfljF5isPsoHjTh/5o56DfuwanxEXUgvzzKtiYwFmrhT+nS6x7cLvD9HYEs/VS6KLAcsP74yMJrnKmekWiDtwsRhBXh0DpdhQ0cyNRkH+tlNPwiyswl6y6n3bIMaOYtBHAZvWsqdLCf2naiiea11LCjm7jWzOGlcZEBcrTkpFY0/8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
